<?php
/**
 * @var Lb\MelhorEnvios\Block\Adminhtml\System\Config\Fieldset\Mapping $block
 */
$_htmlId = $this->getHtmlId() ? $this->getHtmlId() : '_' . uniqid();
$productCode = $block->_getAttributes();
$sizeUnit = ['cm', 'mt'];
$weightUnit = ['kg', 'gr'];
$meCode = ['length','width','height', 'weight'];
$meLabel = $block->_getMeLabel();
$prevValues = [];
$unit = $sizeUnit;

$prevValues = $block->_getStoredMappingValues();

?>

<div class="grid" id="grid<?php /* @noEscape */ echo $_htmlId ?>">
    <table cellpadding="0" cellspacing="0" class="border admin__control-table">
        <tr class="headings" id="headings<?php /* @noEscape */ echo $_htmlId ?>">
            <th><?php /* @escapeNotVerified */ echo __('MelhorEnvios')?></th>
            <th><?php /* @escapeNotVerified */ echo __('Product Attribute')?></th>
            <th><?php /* @escapeNotVerified */ echo __('Product Attribute Unit')?></th>
        </tr>
        <?php foreach($meCode as $key => $meOption):?>
            <tr id="<?php /* @noEscape */ echo $meOption ?>">
                    <td>
                        <label><?php echo $block->escapeHtml($meLabel[$key]) ?>:</label>
                    </td>
                    <td>
                        <select name="groups[melhorenvios][fields][attributesmapping][value][<?php /* @noEscape */ echo $meOption ?>][attribute_code]">
                            <?php foreach($productCode as $option):?>
                                <option value="<?php echo $block->escapeQuote($option->getAttributeCode()) ?>"
                                    <?php /* @noEscape */ echo ( isset($prevValues[$meOption]['attribute_code']) && $prevValues[$meOption]['attribute_code'] == $option->getAttributeCode()) ? "selected='selected'" : "" ?>>
                                    <?php echo $block->escapeHtml($option->getFrontendLabel()) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                    <?php if ($meOption == 'weight') : $unit = $weightUnit; endif;?>
                    <td>
                        <select name="groups[melhorenvios][fields][attributesmapping][value][<?php /* @noEscape */ echo $meOption ?>][unit]">
                            <?php foreach($unit as $_u):?>
                                <option value="<?php /* @noEscape */ echo $_u ?>"
                                        <?php /* @noEscape */ echo (isset($prevValues[$meOption]['unit'])
                                            && $prevValues[$meOption]['unit'] == $_u) ? "selected='selected'" : '' ?>>
                                    <?php /* @noEscape */ echo $_u ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
